name: Build and Push to ACR 

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CONTAINER_REGISTRY_NAME: ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}
  AZURE_CONTAINER_APP_NAME:  ${{ secrets.AZURE_CONTAINER_APP_NAME }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_CR_IMAGE_NAME: ${{ secrets.AZURE_CR_IMAGE_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and Push Docker image to ACR
        run: | 
          az acr build \
            --registry ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }} \
            --image ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ secrets.AZURE_CR_IMAGE_NAME }}:latest \
            ./ContainerDeploymentExample.Api/ContainerDeploymentExample.Api

      - name: Show logged-in identity
        run: az account show
      
      - name: List role assignments for identity
        run: az role assignment list --assignee ${{ secrets.AZURE_CLIENT_ID }} --scope /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.AZURE_RESOURCE_GROUP }} -o table
      
      - name: List container apps in resource group
        run: az containerapp list --resource-group ${{ env.AZURE_RESOURCE_GROUP }} -o table
 
      - name: Verify Container App exists
        run: |
          az containerapp show \
            --name $AZURE_CONTAINER_APP_NAME \
            --resource-group $AZURE_RESOURCE_GROUP

      - name: Deploy to Container App
        run: |
          az containerapp update \
            --name $AZURE_CONTAINER_APP_NAME \
            --resource-group $AZURE_RESOURCE_GROUP \
            --image $AZURE_CONTAINER_REGISTRY_NAME.azurecr.io/$AZURE_CR_IMAGE_NAME:latest
